"""Nasdaq-100 constituents.

Kept as a plain list so it's easy to review/edit. Refreshed occasionally;
the index reconstitutes annually (and with ad-hoc changes). If a ticker is
delisted/renamed, yfinance simply returns no data for it and analyze.py skips it.
"""

# Company display names keyed by ticker. Used for the dashboard labels.
NASDAQ_100 = {
    "AAPL": "Apple",
    "ABNB": "Airbnb",
    "ADBE": "Adobe",
    "ADI": "Analog Devices",
    "ADP": "Automatic Data Processing",
    "ADSK": "Autodesk",
    "AEP": "American Electric Power",
    "AMAT": "Applied Materials",
    "AMD": "Advanced Micro Devices",
    "AMGN": "Amgen",
    "AMZN": "Amazon",
    "APP": "AppLovin",
    "ARM": "Arm Holdings",
    "ASML": "ASML Holding",
    "AVGO": "Broadcom",
    "AZN": "AstraZeneca",
    "BKNG": "Booking Holdings",
    "BKR": "Baker Hughes",
    "CDNS": "Cadence Design Systems",
    "CDW": "CDW Corp",
    "CEG": "Constellation Energy",
    "CHTR": "Charter Communications",
    "CMCSA": "Comcast",
    "COST": "Costco Wholesale",
    "CPRT": "Copart",
    "CRWD": "CrowdStrike",
    "CSCO": "Cisco Systems",
    "CSGP": "CoStar Group",
    "CSX": "CSX Corp",
    "CTAS": "Cintas",
    "CTSH": "Cognizant",
    "DASH": "DoorDash",
    "DDOG": "Datadog",
    "DXCM": "DexCom",
    "EA": "Electronic Arts",
    "EXC": "Exelon",
    "FANG": "Diamondback Energy",
    "FAST": "Fastenal",
    "FTNT": "Fortinet",
    "GEHC": "GE HealthCare",
    "GFS": "GlobalFoundries",
    "GILD": "Gilead Sciences",
    "GOOG": "Alphabet (Class C)",
    "GOOGL": "Alphabet (Class A)",
    "HON": "Honeywell",
    "IDXX": "IDEXX Laboratories",
    "INTC": "Intel",
    "INTU": "Intuit",
    "ISRG": "Intuitive Surgical",
    "KDP": "Keurig Dr Pepper",
    "KHC": "Kraft Heinz",
    "KLAC": "KLA Corp",
    "LIN": "Linde",
    "LRCX": "Lam Research",
    "LULU": "Lululemon Athletica",
    "MAR": "Marriott International",
    "MCHP": "Microchip Technology",
    "MDLZ": "Mondelez International",
    "MELI": "MercadoLibre",
    "META": "Meta Platforms",
    "MNST": "Monster Beverage",
    "MRVL": "Marvell Technology",
    "MSFT": "Microsoft",
    "MU": "Micron Technology",
    "NFLX": "Netflix",
    "NVDA": "NVIDIA",
    "NXPI": "NXP Semiconductors",
    "ODFL": "Old Dominion Freight Line",
    "ON": "ON Semiconductor",
    "ORLY": "O'Reilly Automotive",
    "PANW": "Palo Alto Networks",
    "PAYX": "Paychex",
    "PCAR": "PACCAR",
    "PDD": "PDD Holdings",
    "PEP": "PepsiCo",
    "PLTR": "Palantir Technologies",
    "PYPL": "PayPal Holdings",
    "QCOM": "Qualcomm",
    "REGN": "Regeneron Pharmaceuticals",
    "ROP": "Roper Technologies",
    "ROST": "Ross Stores",
    "SBUX": "Starbucks",
    "SNPS": "Synopsys",
    "TEAM": "Atlassian",
    "TMUS": "T-Mobile US",
    "TSLA": "Tesla",
    "TTD": "The Trade Desk",
    "TTWO": "Take-Two Interactive",
    "TXN": "Texas Instruments",
    "VRSK": "Verisk Analytics",
    "VRTX": "Vertex Pharmaceuticals",
    "WBD": "Warner Bros. Discovery",
    "WDAY": "Workday",
    "XEL": "Xcel Energy",
    "ZS": "Zscaler",
}

TICKERS = list(NASDAQ_100.keys())

if __name__ == "__main__":
    print(f"{len(TICKERS)} tickers")
